# Generated by Django 4.2.20 on 2025-05-16 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detection', '0002_predictionlog_delete_transaction'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('amount', models.FloatField()),
                ('tx_type', models.CharField(max_length=50)),
                ('prediction', models.IntegerField()),
            ],
        ),
    ]
